version: '3.5'
services: 
  backend-hoze:
    build: .
    container_name: hoze 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8090:8000"
  
volumes:
  media:
