version: '3.8'

services:
  backend-ds2:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_ds2_project
    container_name: backend_ds2_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/drf_ds2
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
